! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


MODULE C_PRUNE
USE ISO_FORTRAN_ENV , ONLY : INT64
  IMPLICIT NONE


CONTAINS


  
  SUBROUTINE C_INNER(TREE_SIZE, LEVELS, INDICES_DIM_1, INDICES, CURRENT_LEVEL_PRESENT, CURRENT_LEVEL, STARTING_INDEX_PRESENT, START&
&ING_INDEX, NEXT_INDEX_PRESENT, NEXT_INDEX) BIND(C)
    USE PRUNE, ONLY: INNER
    IMPLICIT NONE
    INTEGER(KIND=INT64), INTENT(IN) :: TREE_SIZE
    INTEGER(KIND=INT64), INTENT(IN) :: LEVELS
    INTEGER, INTENT(IN) :: INDICES_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT), DIMENSION(INDICES_DIM_1) :: INDICES
    LOGICAL, INTENT(IN) :: CURRENT_LEVEL_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: CURRENT_LEVEL
    LOGICAL, INTENT(IN) :: STARTING_INDEX_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: STARTING_INDEX
    LOGICAL, INTENT(IN) :: NEXT_INDEX_PRESENT
    INTEGER(KIND=INT64), INTENT(INOUT) :: NEXT_INDEX
  
    IF (CURRENT_LEVEL_PRESENT) THEN
      IF (STARTING_INDEX_PRESENT) THEN
        IF (NEXT_INDEX_PRESENT) THEN
          CALL INNER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, STARTING_INDEX=STARTING_INDE&
&X, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL INNER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, STARTING_INDEX=STARTING_INDE&
&X)
        END IF
      ELSE
        IF (NEXT_INDEX_PRESENT) THEN
          CALL INNER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL INNER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL)
        END IF
      END IF
    ELSE
      IF (STARTING_INDEX_PRESENT) THEN
        IF (NEXT_INDEX_PRESENT) THEN
          CALL INNER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, STARTING_INDEX=STARTING_INDEX, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL INNER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, STARTING_INDEX=STARTING_INDEX)
        END IF
      ELSE
        IF (NEXT_INDEX_PRESENT) THEN
          CALL INNER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL INNER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES)
        END IF
      END IF
    END IF
  END SUBROUTINE C_INNER
  

  
  SUBROUTINE C_OUTER(TREE_SIZE, LEVELS, INDICES_DIM_1, INDICES, CURRENT_LEVEL_PRESENT, CURRENT_LEVEL, STARTING_INDEX_PRESENT, START&
&ING_INDEX, NEXT_INDEX_PRESENT, NEXT_INDEX) BIND(C)
    USE PRUNE, ONLY: OUTER
    IMPLICIT NONE
    INTEGER(KIND=INT64), INTENT(IN) :: TREE_SIZE
    INTEGER(KIND=INT64), INTENT(IN) :: LEVELS
    INTEGER, INTENT(IN) :: INDICES_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT), DIMENSION(INDICES_DIM_1) :: INDICES
    LOGICAL, INTENT(IN) :: CURRENT_LEVEL_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: CURRENT_LEVEL
    LOGICAL, INTENT(IN) :: STARTING_INDEX_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: STARTING_INDEX
    LOGICAL, INTENT(IN) :: NEXT_INDEX_PRESENT
    INTEGER(KIND=INT64), INTENT(INOUT) :: NEXT_INDEX
  
    IF (CURRENT_LEVEL_PRESENT) THEN
      IF (STARTING_INDEX_PRESENT) THEN
        IF (NEXT_INDEX_PRESENT) THEN
          CALL OUTER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, STARTING_INDEX=STARTING_INDE&
&X, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL OUTER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, STARTING_INDEX=STARTING_INDE&
&X)
        END IF
      ELSE
        IF (NEXT_INDEX_PRESENT) THEN
          CALL OUTER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL OUTER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL)
        END IF
      END IF
    ELSE
      IF (STARTING_INDEX_PRESENT) THEN
        IF (NEXT_INDEX_PRESENT) THEN
          CALL OUTER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, STARTING_INDEX=STARTING_INDEX, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL OUTER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, STARTING_INDEX=STARTING_INDEX)
        END IF
      ELSE
        IF (NEXT_INDEX_PRESENT) THEN
          CALL OUTER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL OUTER(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES)
        END IF
      END IF
    END IF
  END SUBROUTINE C_OUTER
  

  
  SUBROUTINE C_TOP(TREE_SIZE, LEVELS, INDICES_DIM_1, INDICES, CURRENT_LEVEL_PRESENT, CURRENT_LEVEL, STARTING_INDEX_PRESENT, STARTIN&
&G_INDEX, NEXT_INDEX_PRESENT, NEXT_INDEX) BIND(C)
    USE PRUNE, ONLY: TOP
    IMPLICIT NONE
    INTEGER(KIND=INT64), INTENT(IN) :: TREE_SIZE
    INTEGER(KIND=INT64), INTENT(IN) :: LEVELS
    INTEGER, INTENT(IN) :: INDICES_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT), DIMENSION(INDICES_DIM_1) :: INDICES
    LOGICAL, INTENT(IN) :: CURRENT_LEVEL_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: CURRENT_LEVEL
    LOGICAL, INTENT(IN) :: STARTING_INDEX_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: STARTING_INDEX
    LOGICAL, INTENT(IN) :: NEXT_INDEX_PRESENT
    INTEGER(KIND=INT64), INTENT(INOUT) :: NEXT_INDEX
  
    IF (CURRENT_LEVEL_PRESENT) THEN
      IF (STARTING_INDEX_PRESENT) THEN
        IF (NEXT_INDEX_PRESENT) THEN
          CALL TOP(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, STARTING_INDEX=STARTING_INDEX,&
& NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL TOP(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, STARTING_INDEX=STARTING_INDEX)
        END IF
      ELSE
        IF (NEXT_INDEX_PRESENT) THEN
          CALL TOP(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL TOP(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, CURRENT_LEVEL=CURRENT_LEVEL)
        END IF
      END IF
    ELSE
      IF (STARTING_INDEX_PRESENT) THEN
        IF (NEXT_INDEX_PRESENT) THEN
          CALL TOP(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, STARTING_INDEX=STARTING_INDEX, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL TOP(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, STARTING_INDEX=STARTING_INDEX)
        END IF
      ELSE
        IF (NEXT_INDEX_PRESENT) THEN
          CALL TOP(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES, NEXT_INDEX=NEXT_INDEX)
        ELSE
          CALL TOP(TREE_SIZE=TREE_SIZE, LEVELS=LEVELS, INDICES=INDICES)
        END IF
      END IF
    END IF
  END SUBROUTINE C_TOP
  

  
  SUBROUTINE C_LEVEL(TREE_SIZE, LAYER, INDICES_DIM_1, INDICES, FOUND, CURRENT_LEVEL_PRESENT, CURRENT_LEVEL, STARTING_INDEX_PRESENT,&
& STARTING_INDEX, CURRENT_FOUND_PRESENT, CURRENT_FOUND) BIND(C)
    USE PRUNE, ONLY: LEVEL
    IMPLICIT NONE
    INTEGER(KIND=INT64), INTENT(IN) :: TREE_SIZE
    INTEGER(KIND=INT64), INTENT(IN) :: LAYER
    INTEGER, INTENT(IN) :: INDICES_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT), DIMENSION(INDICES_DIM_1) :: INDICES
    INTEGER(KIND=INT64), INTENT(OUT) :: FOUND
    LOGICAL, INTENT(IN) :: CURRENT_LEVEL_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: CURRENT_LEVEL
    LOGICAL, INTENT(IN) :: STARTING_INDEX_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: STARTING_INDEX
    LOGICAL, INTENT(IN) :: CURRENT_FOUND_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: CURRENT_FOUND
  
    IF (CURRENT_LEVEL_PRESENT) THEN
      IF (STARTING_INDEX_PRESENT) THEN
        IF (CURRENT_FOUND_PRESENT) THEN
          CALL LEVEL(TREE_SIZE=TREE_SIZE, LAYER=LAYER, INDICES=INDICES, FOUND=FOUND, CURRENT_LEVEL=CURRENT_LEVEL, STARTING_INDEX=ST&
&ARTING_INDEX, CURRENT_FOUND=CURRENT_FOUND)
        ELSE
          CALL LEVEL(TREE_SIZE=TREE_SIZE, LAYER=LAYER, INDICES=INDICES, FOUND=FOUND, CURRENT_LEVEL=CURRENT_LEVEL, STARTING_INDEX=ST&
&ARTING_INDEX)
        END IF
      ELSE
        IF (CURRENT_FOUND_PRESENT) THEN
          CALL LEVEL(TREE_SIZE=TREE_SIZE, LAYER=LAYER, INDICES=INDICES, FOUND=FOUND, CURRENT_LEVEL=CURRENT_LEVEL, CURRENT_FOUND=CUR&
&RENT_FOUND)
        ELSE
          CALL LEVEL(TREE_SIZE=TREE_SIZE, LAYER=LAYER, INDICES=INDICES, FOUND=FOUND, CURRENT_LEVEL=CURRENT_LEVEL)
        END IF
      END IF
    ELSE
      IF (STARTING_INDEX_PRESENT) THEN
        IF (CURRENT_FOUND_PRESENT) THEN
          CALL LEVEL(TREE_SIZE=TREE_SIZE, LAYER=LAYER, INDICES=INDICES, FOUND=FOUND, STARTING_INDEX=STARTING_INDEX, CURRENT_FOUND=C&
&URRENT_FOUND)
        ELSE
          CALL LEVEL(TREE_SIZE=TREE_SIZE, LAYER=LAYER, INDICES=INDICES, FOUND=FOUND, STARTING_INDEX=STARTING_INDEX)
        END IF
      ELSE
        IF (CURRENT_FOUND_PRESENT) THEN
          CALL LEVEL(TREE_SIZE=TREE_SIZE, LAYER=LAYER, INDICES=INDICES, FOUND=FOUND, CURRENT_FOUND=CURRENT_FOUND)
        ELSE
          CALL LEVEL(TREE_SIZE=TREE_SIZE, LAYER=LAYER, INDICES=INDICES, FOUND=FOUND)
        END IF
      END IF
    END IF
  END SUBROUTINE C_LEVEL
  
END MODULE C_PRUNE

