! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


MODULE C_FAST_SELECT
USE ISO_FORTRAN_ENV , ONLY : REAL64 , INT64
USE SWAP , ONLY : SWAP_I64 , SWAP_R64
  IMPLICIT NONE


CONTAINS


  
  SUBROUTINE C_ARGSELECT_R64(VALUES_DIM_1, VALUES, INDICES_DIM_1, INDICES, K, DIVISOR_PRESENT, DIVISOR, MAX_SIZE_PRESENT, MAX_SIZE)&
& BIND(C)
    USE FAST_SELECT, ONLY: ARGSELECT_R64
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: VALUES_DIM_1
    REAL(KIND=REAL64), INTENT(INOUT), DIMENSION(VALUES_DIM_1) :: VALUES
    INTEGER, INTENT(IN) :: INDICES_DIM_1
    INTEGER(KIND=INT64), INTENT(INOUT), DIMENSION(INDICES_DIM_1) :: INDICES
    INTEGER(KIND=INT64), INTENT(IN) :: K
    LOGICAL, INTENT(IN) :: DIVISOR_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: DIVISOR
    LOGICAL, INTENT(IN) :: MAX_SIZE_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: MAX_SIZE
  
    IF (DIVISOR_PRESENT) THEN
      IF (MAX_SIZE_PRESENT) THEN
        CALL ARGSELECT_R64(VALUES=VALUES, INDICES=INDICES, K=K, DIVISOR=DIVISOR, MAX_SIZE=MAX_SIZE)
      ELSE
        CALL ARGSELECT_R64(VALUES=VALUES, INDICES=INDICES, K=K, DIVISOR=DIVISOR)
      END IF
    ELSE
      IF (MAX_SIZE_PRESENT) THEN
        CALL ARGSELECT_R64(VALUES=VALUES, INDICES=INDICES, K=K, MAX_SIZE=MAX_SIZE)
      ELSE
        CALL ARGSELECT_R64(VALUES=VALUES, INDICES=INDICES, K=K)
      END IF
    END IF
  END SUBROUTINE C_ARGSELECT_R64
  

  
  SUBROUTINE C_ARGSELECT_I64(VALUES_DIM_1, VALUES, INDICES_DIM_1, INDICES, K, DIVISOR_PRESENT, DIVISOR, MAX_SIZE_PRESENT, MAX_SIZE)&
& BIND(C)
    USE FAST_SELECT, ONLY: ARGSELECT_I64
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: VALUES_DIM_1
    INTEGER(KIND=INT64), INTENT(INOUT), DIMENSION(VALUES_DIM_1) :: VALUES
    INTEGER, INTENT(IN) :: INDICES_DIM_1
    INTEGER(KIND=INT64), INTENT(INOUT), DIMENSION(INDICES_DIM_1) :: INDICES
    INTEGER(KIND=INT64), INTENT(IN) :: K
    LOGICAL, INTENT(IN) :: DIVISOR_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: DIVISOR
    LOGICAL, INTENT(IN) :: MAX_SIZE_PRESENT
    INTEGER(KIND=INT64), INTENT(IN) :: MAX_SIZE
  
    IF (DIVISOR_PRESENT) THEN
      IF (MAX_SIZE_PRESENT) THEN
        CALL ARGSELECT_I64(VALUES=VALUES, INDICES=INDICES, K=K, DIVISOR=DIVISOR, MAX_SIZE=MAX_SIZE)
      ELSE
        CALL ARGSELECT_I64(VALUES=VALUES, INDICES=INDICES, K=K, DIVISOR=DIVISOR)
      END IF
    ELSE
      IF (MAX_SIZE_PRESENT) THEN
        CALL ARGSELECT_I64(VALUES=VALUES, INDICES=INDICES, K=K, MAX_SIZE=MAX_SIZE)
      ELSE
        CALL ARGSELECT_I64(VALUES=VALUES, INDICES=INDICES, K=K)
      END IF
    END IF
  END SUBROUTINE C_ARGSELECT_I64
  
END MODULE C_FAST_SELECT

